### ISSUE TITLE
Conventions for direction

### ISSUE THREAD

**Issue by mpmdean** [scikit-beam/rixs#14]
Right now we assume positive y is up and positive x is left to right 

This corresponds to looking in the negative z direction in NSLS-II standards.

**Comment by ambarb** [comment]
@ambarb @bisogni discussed with @mpmdean .

images should be plotted as if the user is looking upstream and with the top of the image corresponding to the top of the CCD. 

The axes definition is:
Positive x is left to right
Positive y is low to high, such that positive y is energy loss.

**Comment by mpmdean** [comment]
Closing since this is merged. It would be nice if the display at the terminal at SIX were inverted so that the physical up direction mirrors the display up direction, but this is a request that belongs elsewhere.
