### ISSUE TITLE
nomenclature for parts of image

### ISSUE THREAD

**Issue by mpmdean** [scikit-beam/rixs#5]
@ambarb suggests low_tth high_tth as names for the different parts of the ccd

high columns is low tth.

**Comment by awalter-bnl** [comment]
I don't have any particular preference for naming but 'tth' is not informative to me at all. What does 'tth' stand for? is whatever it stands for something that is an accepted name in the RIXS (or other) community?

**Comment by ambarb** [comment]
tth refers to 2 theta.  we could do something instead in refer q or qz?
